<a href="https://colab.research.google.com/github/kkimlee/TensorFlow/blob/main/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0%20%EA%B0%9C%EB%85%90%EA%B3%B5%EB%B6%80/Eager_execution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 설치와 기본 사용법



In [3]:
import tensorflow as tf
import cProfile

텐서플로우 2.0이상 버전부터는 즉시 실행이 기본으로 활성화되어 있음

In [5]:
tf.executing_eagerly()

True

세션없이 텐서플로 연산을 실행할 수 있고, 결과 확인이 가능함

In [6]:
x = [[2.]]
m = tf.matmul(x, x)
print("hello, {}".format(m))

hello, [[4.]]


NumPy와 같이 작동함  
NumPy 배열을 tf.Tensor 객체로 변환하여 tf.Tensor.numpy 메서드를 이용해 객체 값을 NumPy ndarray로 반환

In [8]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [9]:
# 브로드캐스팅
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [10]:
# 연산자 오버로딩
print(a * b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [11]:
# NumPy값 사용
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [12]:
# Tensor를 numpy 값으로 변환
print(a.numpy())

[[1 2]
 [3 4]]


# 동적인 제어

즉시 실행을 통해 모델이 실행되는 동안에도 동적인 제어가 가능함

In [15]:
def fizzbuzz(max_num):
  counter = tf.constant(0)
  max_num = tf.convert_to_tensor(max_num)
  for num in range(1, max_num.numpy()+1):
    num = tf.constant(num)
    if int(num % 3) == 0 and int(num % 5) == 0:
      print('FizzBuzz')
    elif int(num % 3) == 0:
      print('Fizz')
    elif int(num % 5) == 0:
      print('Buzz')
    else:
      print(num.numpy())
    counter += 1

In [16]:
fizzbuzz(15)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


# 그래디언트 계산

실행 중에 그래디언트를 계산하고 이용하기 위해 tf.GradientTape을 이용할 수 있음    

실행 중에 모든 연산은 tape에 저장되며, tape을 거꾸로 연산하여 그래디언트를 계산 한 후 tape은 사라짐  
  
tf.GradientTape은 오직 하나의 그래디언트만을 계산할 수 있고 추가적인 호출은 실행중 에러(runtime error)를 발생시킴

In [17]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
  loss = w * w

grad = tape.gradient(loss, w)
print(grad)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


# 모델 훈련

MNIST 모델 훈련

In [18]:
# mnist 데이터 가져오기 및 포맷 맞추기
(mnist_images, mnist_labels), _ = tf.keras.datasets.mnist.load_data()

dataset = tf.data.Dataset.from_tensor_slices(
    (tf.cast(mnist_images[..., tf.newaxis]/255, tf.float32),
     tf.cast(mnist_labels, tf.int64)))
dataset = dataset.shuffle(1000).batch(32)

11493376/11490434 [==============================] - 0s 0us/step
